language: python
python:
  - "2.7"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
  - pip install coveralls

before_script:
  - sudo touch /var/log/fiware-skuld
  - sudo chown travis /var/log/fiware-skuld

# command to run tests
script:
  cd tests/units;nosetests --with-coverage --cover-package=./ --exe

after_success:
  coveralls
